@startuml
/'
 ' Samples for Class Diagrams
 '/
!include style-all.puml

namespace Package1 {
  class BaseClass
}
namespace Package2 {
  Package1.BaseClass <|-- Class1
  Class1 *- Class2
}
namespace Package3 {
  Package1.BaseClass <|-- Class1
  Class1 *- Class2
}

@enduml
