@startuml
/'
 ' Samples for Class Diagrams
 '/
!include style-all.puml

class ClassName {
  {field} + publicfield : String = ""
  {field} - privatefield : int
  {field} # protectedfield : double
  {field} ~ protectedfieldInPackage : Object
  {classifier} staticField : Object2

  {method} + publicMethod(s : String, v : int) : type
  {method} - privateMethod() : int
  {method} # protectedMethod() : double
  {method} ~ protectedMethodInPackage() : Object
  {abstract} abstract() : void
}

@enduml
