@startuml
/'
 ' Samples for Class Diagrams
 '/
show circle

interface InterfaceClass
abstract AbstractClass
class ImplementClass
class ClassName <<Stereotype>>

enum Enum {
  ONE
  TWO
  THREE
}

annotation Annotation

@enduml
