@startuml
/'
 ' Style for PlantUML'
 '/

' Shadowing
skinparam shadowing false

' Resolution for output image
skinparam dpi 300

' Default font'
skinparam default{
  FontColor Black
  FontName sans-serif
  FontSize 14
  FontStyle normal
  MonospacedFontName monospace
  TextAlign left
}

' Note
skinparam note {
  BackgroundColor LemonChiffon
  BorderColor Black
  BorderThickness 1
  FontColor Black
  FontName sans-serif
  FontSize 10
  FontStyle normal
}

' Actor
skinparam actor {
  BackgroundColor WhiteSmoke
  BorderColor Black
  FontColor Black
  FontName sans-serif
  FontSize 14
  FontStyle normal
  StereotypeFontColor Black
  StereotypeFontName monospace
  StereotypeFontSize 10
  StereotypeFontStyle normal
}

' Boundary
skinparam boundary {
  BackgroundColor WhiteSmoke
  BorderColor Black
  FontColor Black
  FontName sans-serif
  FontSize 14
  FontStyle normal
  StereotypeFontColor Black
  StereotypeFontName monospace
  StereotypeFontSize 10
  StereotypeFontStyle normal
}

' Control
skinparam control {
  BackgroundColor WhiteSmoke
  BorderColor Black
  FontColor Black
  FontName sans-serif
  FontSize 14
  FontStyle normal
  StereotypeFontColor Black
  StereotypeFontName monospace
  StereotypeFontSize 10
  StereotypeFontStyle normal
}

' Entity
skinparam entity {
  BackgroundColor WhiteSmoke
  BorderColor Black
  FontColor Black
  FontName sans-serif
  FontSize 14
  FontStyle normal
  StereotypeFontColor Black
  StereotypeFontName monospace
  StereotypeFontSize 10
  StereotypeFontStyle normal
}

' Database
skinparam database {
  BackgroundColor WhiteSmoke
  BorderColor Black
  FontColor Black
  FontName sans-serif
  FontSize 14
  FontStyle normal
  StereotypeFontColor Black
  StereotypeFontName monospace
  StereotypeFontSize 10
  StereotypeFontStyle normal
}

' Participant
skinparam participant {
  BackgroundColor WhiteSmoke
  BorderColor Black
  FontColor Black
  FontName sans-serif
  FontSize 14
  FontStyle normal
}

' Sequence Diagrams
skinparam sequence {
  ' Life line
  LifeLineBackgroundColor White
  LifeLineBorderColor Black
  LifeLineBorderThickness 1

  ' Arrow
  ArrowColor Black
  ArrowFontName sans-serif
  ArrowFontColor Black
  ArrowFontSize 10
  ArrowFontStyle normal
  ArrowThickness 1
  MessageAlign center

  ' Group
  GroupBackgroundColor WhiteSmoke
  GroupBodyBackgroundColor White
  GroupBorderColor Black
  GroupBorderThickness 1
  GroupFontColor Black
  GroupFontName sans-serif
  GroupFontSize 10
  GroupFontStyle normal
  GroupHeaderFontColor Black
  GroupHeaderFontName sans-serif
  GroupHeaderFontSize 10
  GroupHeaderFontStyle normal

  ' Reference
  ReferenceBackgroundColor White
  ReferenceBorderColor Black
  ReferenceBorderThickness 1
  ReferenceFontColor Black
  ReferenceFontName sans-serif
  ReferenceFontSize 10
  ReferenceFontStyle normal
  ReferenceHeaderBackgroundColor WhiteSmoke


  ' Actor and Participant
  ActorBorderThickness 1.5
  ParticipantBorderThickness 1.5
}

@enduml
